feat: enforce main branch restriction for release workflow execution

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -12,16 +12,22 @@ on:
 jobs:
   update-latest:
     runs-on: ubuntu-latest
-    # only run on main branch
-    if: github.event.branch == 'main'
     # ensure only one pipeline is running this workflow at a time
     concurrency:
       group: ${{ github.workflow }}-${{ github.ref }}
     steps:
+      # only run on main branch
+      - name: Check branch
+        if: github.event.branch != 'main'
+        run: |
+          echo "::error::Workflow can only be run on main branch"
+          exit 1
+
       - name: Checkout code
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
+
       - name: release
         run: |
           export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
